# Containerfile

FROM ghcr.io/freebsd/freebsd-runtime:15.snap

#
# Mimic Sonatype image properties , arguments , and environment
#
LABEL name="Nexus Repository Manager -- FreeBSD" \
      maintainer="Mark LaPointe <mark@cloudbsd.org>" \
      vendor=Sonatype \
      version="3.80.0-06" \
      release="3.80.0" \
      url="https://sonatype.com" \
      summary="The Nexus Repository Manager server \
          with universal support for popular component formats." \
      description="The Nexus Repository Manager server \
          with universal support for popular component formats." \
      run="podman run -d --name NAME \
          -p 8081:8081 \
          IMAGE" \
      stop="podman stop NAME" \
      com.sonatype.license="Apache License, Version 2.0" \
      com.sonatype.name="Nexus Repository Manager base image"

ARG NEXUS_VERSION=3.80.0-06
ARG NEXUS_DOWNLOAD_URL=https://download.sonatype.com/nexus/3/nexus-${NEXUS_VERSION}-linux-x86_64.tar.gz

# configure nexus runtime
ENV SONATYPE_DIR=/usr/local
ENV NEXUS_HOME=${SONATYPE_DIR}/nexus \
    NEXUS_DATA=/nexus-data \
    NEXUS_CONTEXT='' \
    SONATYPE_WORK=${SONATYPE_DIR}/sonatype-work

#
# Start FreeBSD Styling
#

#Update base components and install dependencies
RUN sed -EI -e s/quarterly/latest/ /etc/pkg/FreeBSD.conf
RUN env ASSUME_ALWAYS_YES=yes IGNORE_OS_VERSION=yes pkg bootstrap -r FreeBSD
RUN env ASSUME_ALWAYS_YES=yes IGNORE_OS_VERSION=yes pkg update
RUN env ASSUME_ALWAYS_YES=yes IGNORE_OS_VERSION=yes pkg install -y FreeBSD-utilities openjdk17 zsh

#
# Add Nexus User And Group
#

RUN pw groupadd nexus
RUN pw useradd nexus -s /usr/sbin/nologin -G nexus

# Download and place the Nexus 3 Application
RUN fetch ${NEXUS_DOWNLOAD_URL}
RUN tar xvzf nexus-${NEXUS_VERSION}-linux-x86_64.tar.gz && \
 rm nexus-${NEXUS_VERSION}-linux-x86_64.tar.gz && \
 mv nexus-* /usr/local/nexus && \
 mkdir -p ${NEXUS_DATA} && \
 chown -R nexus:nexus ${NEXUS_DATA} && \
 ln -s ${NEXUS_DATA} ${SONATYPE_WORK} && \
 ln -s ${NEXUS_DATA} ${NEXUS_HOME}/sonatype-work


# Cleanup
RUN pkg clean -y

# Place entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

EXPOSE 8081
#USER nexus

# ENV INSTALL4J_ADD_VM_PARAMS="-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs"
CMD [ "/entrypoint.sh"]