#
# Use this to easily deploy this image with podman-compose
#
services:
  nexus:
    image: localhost/cloudbsd/nexus3:FreeBSD-14.3-3.80.0-06
    volumes:
      - "nexus-data:/usr/local/sonatype-work/nexus3"
    ports:
      - "8081:8081"
volumes:
  nexus-data: {
  }